CREATE TABLE JOGOS (
    ID INT NOT NULL AUTO_INCREMENT,
    TITULO VARCHAR(255) NOT NULL,
    DESENVOLVEDORA VARCHAR(255) NOT NULL,
    DISTRIBUIDORA VARCHAR(255) NULL,
    IDIOMA VARCHAR(50) NOT NULL,
    NUMERO_JOGADORES VARCHAR(4) NOT NULL,
    LANCAMENTO VARCHAR(4) NOT NULL,
    GENERO VARCHAR(50) NOT NULL,
    SISTEMA_OPERACIONAL VARCHAR(50) NULL,
    PROCESSADOR VARCHAR(255) NOT NULL,
    MEMORIA VARCHAR(50) NOT NULL,
    PLACA_DE_VIDEO VARCHAR(255) NOT NULL,
    ARMAZENAMENTO VARCHAR(255) NOT NULL,
    ATIVO INT DEFAULT 1 NOT NULL,
    CONSTRAINT GAMES_PK PRIMARY KEY (ID)
    );